<?php

return [

    "projects" => [
        [
            "title" => "Discord",
            "slug" => "",
            "cover_image" => "uploads/IpVuoi5gAYsAnmzm6XisVqWgQiPQLfiNEHGS05qn.png",
            "content" => "Riproduzione del sito Discord con HTML e CSS",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/htmlcss-discord",
            "date_time" => "2023-02-07",
        ],
        [
            "title" => "DropBox",
            "slug" => "",
            "cover_image" => "uploads/4uaTUYttPZjODxyqZdXIkZizxiMuGE43xG7Wnvu8.png",
            "content" => "Riproduzione del sito Dropbox con HTML e CSS",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/htmlcss-dropbox",
            "date_time" => "2023-02-15",
        ],
        [
            "title" => "Responsive Layout",
            "slug" => "",
            "cover_image" => "uploads/responsive_layouts.png",
            "content" => "Riproduzione di un sito Responsive con HTML e CSS",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/htmlcss-responsive-layout",
            "date_time" => "2023-02-21",
        ],
        [
            "title" => "Spotify",
            "slug" => "",
            "cover_image" => "uploads/G3eImuX1JBXkVwBgzfiVPdbAaJPVvy6ZbuAut3wD.jpg",
            "content" => "Riproduzione della piattaforma streaming di musica Spotifi con HTML e CSS",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/html-css-spotifyweb",
            "date_time" => "2023-02-24",
        ],
        [
            "title" => "Bootstrap Dashboard",
            "slug" => "",
            "cover_image" => "uploads/3RpBqjkyFzkAFAPMA9d6ohwjVUv5P7G3vC6s3fA6.png",
            "content" => "Riproduzione di una Dashboard HTML e CSS",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/html-css-bootstrap-dashboard",
            "date_time" => "2023-03-02",
        ],
        [
            "title" => "Campo Minato",
            "slug" => "",
            "cover_image" => "uploads/campo_minato.png",
            "content" => "Riproduzione del campo minato con JavaScript, HTML e CSS",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/js-campominato-dom",
            "date_time" => "2023-03-20",
        ],
        [
            "title" => "Social Posts",
            "slug" => "",
            "cover_image" => "uploads/social_post.png",
            "content" => "Riproduzione di un social media con JavaScript, HTML e CSS",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/js-social-posts",
            "date_time" => "2023-03-24",
        ],
        [
            "title" => "Whatsapp",
            "slug" => "",
            "cover_image" => "uploads/3WS9WVOArHexRBNeW7BDm8rx34tUolCEsk02Pnad.jpg",
            "content" => "Riproduzione della piattaforma di messaggistica Wh...",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/vue-boolzapp",
            "date_time" => "2023-04-04",
        ],
        [
            "title" => "DC Comics",
            "slug" => "",
            "cover_image" => "uploads/hxpIWGwDyosmXEjX26976Mg8ASruTevgklA2MmDA.png",
            "content" => "Riproduzione del sito della DC Comics con Vite, Vu...",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/vite-comics",
            "date_time" => "2023-04-14",
        ],
        [
            "title" => "Yu-Gi-oh",
            "slug" => "",
            "cover_image" => "uploads/yu-gi-oh.png",
            "content" => "Riproduzione del sito Yu-Gi-Oh per ricercare le carte, fatto con VueJs, JavaScript, HTML e CSS",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/vite-yu-gi-oh",
            "date_time" => "2023-04-18",
        ],
        [
            "title" => "Netflix",
            "slug" => "",
            "cover_image" => "uploads/MUGhMt5XIgMaGiHLN3Y3zok02LJgTLyqc3THH4cJ.jpg",
            "content" => "Riproduzione della piattaforma di streaming video ...",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/vite-boolflix",
            "date_time" => "2023-04-21",
        ],
        [
            "title" => "DC Comics Laravel",
            "slug" => "",
            "cover_image" => "uploads/hxpIWGwDyosmXEjX26976Mg8ASruTevgklA2MmDA.png",
            "content" => "Riproduzione del sito DC Comics con Laravel, PHP, ...",
            "site_link" => "https://github.com/Dan97O?tab=repositories",
            "source_code" => "https://github.com/Dan97O/laravel-comics",
            "date_time" => "2023-05-25",
        ],
    ],

];
